MethodError: no constructors have been defined for SyntaxTree fixed when doing alphabet_int = ExplicitAlphabet(Atom.(1:10)) grammar_int = SoleLogics.CompleteFlatGrammar(alphabet_int, SoleLogics.BASE_OPERATORS) formulas(grammar_int; maxdepth=2, nformulas=10)